%% Path setup
addpath("feature-extraction")
addpath("lib")
addpath("preprocessing")
addpath("data-wrangling")
addpath("supervised-classification")
addpath("supervised-classification/classifiers")
addpath("supervised-classification/data-sampling")
addpath("supervised-classification/cnn2d-default-training")
addpath("supervised-classification/hyperparameter-tuning")
