% SPDX-License-Identifier: BSD-3-Clause

%% Path setup
addpath(".")
addpath("feature-extraction")
addpath("lib")
addpath("preprocessing")
addpath("data-wrangling")
addpath("supervised-classification")
addpath("supervised-classification" + filesep + "classifiers")
addpath("supervised-classification" + filesep + "training")
addpath("supervised-classification" + filesep + "training" + filesep + "data-sampling")
addpath("supervised-classification" + filesep + "training" + filesep + "cnn2d-default-training")
addpath("supervised-classification" + filesep + "training" + filesep + "hyperparameter-tuning")
addpath("supervised-classification" + filesep + "training" + filesep + "final-training")
addpath("supervised-classification" + filesep + "testing")
addpath("figures")
addpath("dataset-analysis")
addpath("results-analysis")
addpath("changepoint-detection")
addpath("changepoint-detection" + filesep + "gfpop")
