function createCNN2d7LayerHyperparamSearchRange()

% SPDX-License-Identifier: BSD-3-Clause

CLASSIFIER_NAME = "CNN2d7Layer";

% Set up data paths
beehiveDataSetup;

% Create the optimizable variables that will be used by bayesopt
optimizableParams = [
    optimizableVariable("FilterHeight1",[1,2],Type="integer"),...
    optimizableVariable("FilterWidth1",[2,64],Type="integer"),...
    optimizableVariable("NFilters1",[2,64],Type="integer"),...
    optimizableVariable("FilterHeight2",[1,2],Type="integer"),...
    optimizableVariable("FilterWidth2",[2,64],Type="integer"),...
    optimizableVariable("NFilters2",[2,64],Type="integer"),...
    optimizableVariable("FilterHeight3",[1,2],Type="integer"),...
    optimizableVariable("FilterWidth3",[2,32],Type="integer"),...
    optimizableVariable("NFilters3",[2,64],Type="integer"),...
    optimizableVariable("FilterHeight4",[1,2],Type="integer"),...
    optimizableVariable("FilterWidth4",[2,32],Type="integer"),...
    optimizableVariable("NFilters4",[2,64],Type="integer"),...
    optimizableVariable("FilterHeight5",[1,2],Type="integer"),...
    optimizableVariable("FilterWidth5",[2,16],Type="integer"),...
    optimizableVariable("NFilters5",[2,64],Type="integer"),...
    optimizableVariable("FilterHeight6",[1,2],Type="integer"),...
    optimizableVariable("FilterWidth6",[2,16],Type="integer"),...
    optimizableVariable("NFilters6",[2,64],Type="integer"),...
    optimizableVariable("FilterHeight7",[1,2],Type="integer"),...
    optimizableVariable("FilterWidth7",[2,8],Type="integer"),...
    optimizableVariable("NFilters7",[2,64],Type="integer"),...
    optimizableVariable("FalseNegativeCost",[1 10],Type="integer")
];

save(trainingDataDir + filesep + CLASSIFIER_NAME ...
    + "HyperparameterSearchValues","optimizableParams","-v7.3");

end
